$axure.loadCurrentPage({
  "url":"关于git.html",
  "generationDate":new Date(1502030602473.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"758f5bbf6eed448294681972ab517370",
    "type":"Axure:Page",
    "name":"关于GIT",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c07168bfab4e4217af84c7cdea38499d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":790,
              "height":270},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2eef214a79643fda2a7bc3f73be383e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":790,
                  "height":270},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于git/u0.png"}},
{
          "id":"9df3e37c96614a469584416fcbec4739",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":40,
              "y":40},
            "size":{
              "width":60,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1438968b05d4647ba739bf151939f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":40},
                "size":{
                  "width":60,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ceeaf08865d7421e85b5cce9aa8e772f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":340},
            "size":{
              "width":790,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b49b35d301e485eab00b1e9b7cef689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":340},
                "size":{
                  "width":790,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于git/u4.png"}},
{
          "id":"ca28ba5176294076b933a0a9b92a7940",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":40,
              "y":360},
            "size":{
              "width":296,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fcfca9b5b94c048e574a58b1d222d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":360},
                "size":{
                  "width":296,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7880c880638c46fb941aad582858af71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":40,
              "y":71},
            "size":{
              "width":566,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ac04faae6245f7b7c535faeeae154f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":71},
                "size":{
                  "width":566,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ccd25900f61430983bb861f24dd723d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":40,
              "y":91},
            "size":{
              "width":630,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c545a52d3f244d4fa211e807a43ccb8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":91},
                "size":{
                  "width":630,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd69debbb67a41b7a794b0d0e95a0cac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":235,
              "y":129},
            "size":{
              "width":265,
              "height":51},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4c852e30c4427dbd1a7458f2f09429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":235,
                  "y":129},
                "size":{
                  "width":265,
                  "height":51},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于git/u12.png"}},
{
          "id":"ba275ad9ed864f72a03ef623b60b4cc7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF212121,
              "opacity":1},
            "location":{
              "x":300,
              "y":260},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a0a2895689f405b80b53c94d8fd77c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF212121,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":260},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]},
{
          "id":"9f21fdea345c40f79c3591591da51ba0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":408.5,
              "y":190},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95205506ac2d40179d7e13ed776cf866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408.5,
                  "y":190},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "c07168bfab4e4217af84c7cdea38499d":{
      "scriptId":"u0"},
    "d2eef214a79643fda2a7bc3f73be383e":{
      "scriptId":"u1"},
    "9df3e37c96614a469584416fcbec4739":{
      "scriptId":"u2"},
    "d1438968b05d4647ba739bf151939f00":{
      "scriptId":"u3"},
    "ceeaf08865d7421e85b5cce9aa8e772f":{
      "scriptId":"u4"},
    "6b49b35d301e485eab00b1e9b7cef689":{
      "scriptId":"u5"},
    "ca28ba5176294076b933a0a9b92a7940":{
      "scriptId":"u6"},
    "e0fcfca9b5b94c048e574a58b1d222d4":{
      "scriptId":"u7"},
    "7880c880638c46fb941aad582858af71":{
      "scriptId":"u8"},
    "c1ac04faae6245f7b7c535faeeae154f":{
      "scriptId":"u9"},
    "4ccd25900f61430983bb861f24dd723d":{
      "scriptId":"u10"},
    "c545a52d3f244d4fa211e807a43ccb8c":{
      "scriptId":"u11"},
    "cd69debbb67a41b7a794b0d0e95a0cac":{
      "scriptId":"u12"},
    "ab4c852e30c4427dbd1a7458f2f09429":{
      "scriptId":"u13"},
    "ba275ad9ed864f72a03ef623b60b4cc7":{
      "scriptId":"u14"},
    "6a0a2895689f405b80b53c94d8fd77c6":{
      "scriptId":"u15"},
    "9f21fdea345c40f79c3591591da51ba0":{
      "scriptId":"u16"},
    "95205506ac2d40179d7e13ed776cf866":{
      "scriptId":"u17"}}});