$axure.loadCurrentPage({
  "url":"关于请求和响应.html",
  "generationDate":new Date(1502030600013.53),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2d3b4c134c9846608789e80457eb0cfb",
    "type":"Axure:Page",
    "name":"关于请求和响应",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8d9a2c1d09b44aeaa30735448fcf2e4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":130},
            "size":{
              "width":60,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a2453444904ed5bf2910c92ba29226",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":130},
                "size":{
                  "width":60,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于请求和响应/u0.png"}},
{
          "id":"ac1fb30a36054bf6b85123a3cf350fd0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":440},
            "size":{
              "width":50,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"628ac8f862bb4048bcb94051f9a1f1b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":440},
                "size":{
                  "width":50,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于请求和响应/u2.png"}},
{
          "id":"ed813ee5c2af4f76bddc008e67ad262e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":360},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bde3411f97434e3cac114e60e5bf38ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":360},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于请求和响应/u4.png"}},
{
          "id":"cc2765ad3a2e4abdb7c645491d785699",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":480},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2170952c2ce482cb69d106a69142d86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":480},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]},
{
          "id":"0da8f44df4ec4acdbbe9643c584e083f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":390},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9325ab76ea8c4aae84f240ba521b19b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":390},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]},
{
          "id":"8853fcc105aa4254b5855bbefa69a3a7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":170},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63a8d6396d2743728d5c594ebd050572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":170},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]},
{
          "id":"f83e88bafe44425c946b9d1d3e8ec998",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":90},
            "size":{
              "width":560,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d348c3a2592045e2bad1e302bf925a2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":90},
                "size":{
                  "width":560,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/关于请求和响应/u12.png"}},
{
          "id":"d97a48ed0ff94a27bc10513f886b5d49",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":390},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF616161}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33130b460e374ab7bbaa4959b110cc4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":390},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF616161}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a8d9a2c1d09b44aeaa30735448fcf2e4":{
      "scriptId":"u0"},
    "10a2453444904ed5bf2910c92ba29226":{
      "scriptId":"u1"},
    "ac1fb30a36054bf6b85123a3cf350fd0":{
      "scriptId":"u2"},
    "628ac8f862bb4048bcb94051f9a1f1b4":{
      "scriptId":"u3"},
    "ed813ee5c2af4f76bddc008e67ad262e":{
      "scriptId":"u4"},
    "bde3411f97434e3cac114e60e5bf38ed":{
      "scriptId":"u5"},
    "cc2765ad3a2e4abdb7c645491d785699":{
      "scriptId":"u6"},
    "a2170952c2ce482cb69d106a69142d86":{
      "scriptId":"u7"},
    "0da8f44df4ec4acdbbe9643c584e083f":{
      "scriptId":"u8"},
    "9325ab76ea8c4aae84f240ba521b19b2":{
      "scriptId":"u9"},
    "8853fcc105aa4254b5855bbefa69a3a7":{
      "scriptId":"u10"},
    "63a8d6396d2743728d5c594ebd050572":{
      "scriptId":"u11"},
    "f83e88bafe44425c946b9d1d3e8ec998":{
      "scriptId":"u12"},
    "d348c3a2592045e2bad1e302bf925a2e":{
      "scriptId":"u13"},
    "d97a48ed0ff94a27bc10513f886b5d49":{
      "scriptId":"u14"},
    "33130b460e374ab7bbaa4959b110cc4f":{
      "scriptId":"u15"}}});